### ISSUE TITLE
Use stylish for Code Format

### ISSUE THREAD

**Issue by oshyshko** [moodmosaic/ide-haskell-ghcide#1]
It looks like `ghcide` doesn't have an idea of code formatting (correct me, if I am mistaken here).

It would be nice to have [code format feature in atome-ide-ui](https://github.com/facebookarchive/atom-ide-ui/blob/master/docs/code-format.md) implemented using `stylish` command, similarly to how it's done in [language-haskell](https://github.com/atom-haskell/language-haskell).

**Comment by moodmosaic** [comment]
>similarly to how it's done in [language-haskell](https://github.com/atom-haskell/language-haskell)

I'm not sure I follow(?)

**Comment by moodmosaic** [comment]
Perhaps via `atom-beautify` which [supports `stylish-haskell`](https://github.com/jaspervdj/stylish-haskell#atom-integration)? The reason I didn't consider something like this is because I just format my code manually, more or less based on [this style guide](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/STYLE_GUIDE.md).

**Comment by oshyshko** [comment]
`atom-beautify` works fine. Thanks.

**Comment by oshyshko** [comment]
It looks like `atom-beautify` it doesn't pick `.stylish-haskell.yaml` in project root, so it's not very usable (for example, I very much prefer to have `language_extensions:` in [one file](https://github.com/oshyshko/adventofcode/blob/master/.stylish-haskell.yaml#L231-L238), rather than scattered and duplicated as pragmas across `.hs` files.

Another thing is that it makes [current installation](https://atom.io/packages/ide-haskell-ghcide) and configuration even more complex and something that users need to discover and setup by themselves (which I, as a user, failed to figure out).

It would be nice to have a one-stop solution.

**Comment by moodmosaic** [comment]
Oh, I see what you mean. Though, we shouldn't couple `ide-haskell-ghcide` with other tools. The vision I have for `ide-haskell-ghcide` is that it will only be responsible for I/O between Atom and ghcide.

Isn't this also how the Visual Studio Code plugin works?

---

In my experience, when doing Haskell development, your tooling should be *fairly* minimal:
* Text editor of your choice
* Syntax highlighting
* Make heavy use of GHCi
* *...and that's pretty much it.*
* (Optional) Use ghcid
* (Optional) Use ghcid*e*

### Example

Say you want to run `stylish-haskell` from inside your favorite editor, then that should be *decoupled* from all the above.

So you'd just `stack build --copy-compiler-tool stylish-haskell` (or use Nix), and then `stack exec -- atom` and bind a shortcut key.

``` bash
# That's for formatting all files, but you can also tweak it to run for a single file.

:! find . -name '*.hs' | xargs stylish-haskell -i # GHCi
 $ find . -name '*.hs' | xargs stylish-haskell -i # Bash
```

(I understand that this might be far from *out of the box (OOTB)*, but the issue with *works OOTB* is that then you need to deal with the plugin(s) *and* the tooling itself.)

---

The UNIX philosophy is documented by Doug McIlroy in the Bell System Technical Journal from 1978: Make each program *do one thing well*.
